# app/yacht_profiles/default_cabin_cruiser_20_25ft.py

DEFAULT_CABIN_CRUISER_20_25FT = {
    "yacht": {
        "id": "marex-21-001",
        "name": "Marex Flexi 21 #001",
    },
    "hardware": {
        "buses": [
            {
                "id": "io_main",
                "type": "modbus_tcp",
                "vendor": "generic",
                "host": "192.168.10.50",
                "port": 502,
                "unit_id": 1,
            }
        ],
    },
    "devices": [
        {
            "id": "salon_lights",
            "name": "Salon Lights",
            "zone": "Salon",
            "type": "light",
            "state": False,
            "hw_id": "modbus:io_main:coil:0",
            "ai_control": "allowed",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "cabin_lights",
            "name": "Cabin Lights",
            "zone": "Cabin",
            "type": "light",
            "state": False,
            "hw_id": "modbus:io_main:coil:1",
            "ai_control": "allowed",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "cockpit_lights",
            "name": "Cockpit Lights",
            "zone": "Cockpit",
            "type": "light",
            "state": False,
            "hw_id": "modbus:io_main:coil:2",
            "ai_control": "allowed",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "nav_lights",
            "name": "Navigation Lights (port/starboard/stern)",
            "zone": "Exterior",
            "type": "light",
            "state": False,
            "hw_id": "modbus:io_main:coil:3",
            "ai_control": "limited",
            "max_runtime_seconds": None,
            "requires_human_ack": True,
        },
        {
            "id": "anchor_light",
            "name": "Anchor Light",
            "zone": "Mast",
            "type": "light",
            "state": False,
            "hw_id": "modbus:io_main:coil:4",
            "ai_control": "limited",
            "max_runtime_seconds": None,
            "requires_human_ack": True,
        },
        {
            "id": "deck_flood_light",
            "name": "Foredeck Flood Light",
            "zone": "Foredeck",
            "type": "light",
            "state": False,
            "hw_id": "modbus:io_main:coil:5",
            "ai_control": "allowed",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "courtesy_lights",
            "name": "Courtesy / Step Lights",
            "zone": "Cockpit/Side Decks",
            "type": "light",
            "state": False,
            "hw_id": "modbus:io_main:coil:6",
            "ai_control": "allowed",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "freshwater_pump",
            "name": "Fresh Water Pump",
            "zone": "Technical",
            "type": "pump",
            "state": False,
            "hw_id": "modbus:io_main:coil:7",
            "ai_control": "limited",
            "max_runtime_seconds": 600,
            "requires_human_ack": False,
        },
        {
            "id": "shower_sump_pump",
            "name": "Shower Sump Pump",
            "zone": "Cabin / Bilge",
            "type": "pump",
            "state": False,
            "hw_id": "modbus:io_main:coil:8",
            "ai_control": "limited",
            "max_runtime_seconds": 600,
            "requires_human_ack": False,
        },
        {
            "id": "bilge_pump_main",
            "name": "Main Bilge Pump",
            "zone": "Bilge",
            "type": "pump",
            "state": False,
            "hw_id": "modbus:io_main:coil:9",
            "ai_control": "limited",
            "max_runtime_seconds": 600,
            "requires_human_ack": True,
        },
        {
            "id": "bilge_pump_auto_override",
            "name": "Bilge Auto Override",
            "zone": "Bilge",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:coil:10",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": True,
        },
        {
            "id": "fridge",
            "name": "Fridge",
            "zone": "Galley",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:coil:11",
            "ai_control": "limited",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "cabin_fan",
            "name": "Cabin Ventilation Fan",
            "zone": "Cabin",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:coil:12",
            "ai_control": "allowed",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "windscreen_wiper",
            "name": "Windscreen Wiper",
            "zone": "Helm",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:coil:13",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": True,
        },
        {
            "id": "horn",
            "name": "Horn",
            "zone": "Helm",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:coil:14",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": True,
        },
        {
            "id": "inverter_power",
            "name": "Inverter On/Off",
            "zone": "Technical",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:coil:15",
            "ai_control": "limited",
            "max_runtime_seconds": None,
            "requires_human_ack": True,
        },
        {
            "id": "cabin_heater",
            "name": "Cabin Heater / Diesel Heater",
            "zone": "Cabin/Technical",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:coil:16",
            "ai_control": "limited",
            "max_runtime_seconds": None,
            "requires_human_ack": True,
        },
        {
            "id": "bilge_float_high",
            "name": "Bilge High Level Float",
            "zone": "Bilge",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:input:0",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "bilge_float_auto",
            "name": "Bilge Auto Float",
            "zone": "Bilge",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:input:1",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "cabin_door_contact",
            "name": "Cabin Door Contact",
            "zone": "Cabin",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:input:2",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "engine_room_door_contact",
            "name": "Engine Space Access Hatch",
            "zone": "Engine Room / Aft",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:input:3",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "helm_anchor_scene_button",
            "name": "Helm “At Anchor” Button",
            "zone": "Helm",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:input:4",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "helm_night_scene_button",
            "name": "Helm “Night Mode” Button",
            "zone": "Helm",
            "type": "switch",
            "state": False,
            "hw_id": "modbus:io_main:input:5",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "shore_power_present",
            "name": "Shore Power Present",
            "zone": "Technical",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:input:6",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "battery_low_alarm",
            "name": "Battery Low Alarm Input",
            "zone": "Technical",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:input:7",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "fresh_water_tank_level",
            "name": "Fresh Water Tank Level",
            "zone": "Tanks",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:holding:0",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "fuel_tank_level",
            "name": "Fuel Tank Level",
            "zone": "Tanks",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:holding:1",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "battery_voltage_house",
            "name": "House Battery Voltage",
            "zone": "Electrical",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:holding:2",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "battery_voltage_engine",
            "name": "Engine Battery Voltage",
            "zone": "Electrical",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:holding:3",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
        {
            "id": "engine_room_temp",
            "name": "Engine Room Temperature",
            "zone": "Engine Room",
            "type": "sensor",
            "state": None,
            "hw_id": "modbus:io_main:holding:4",
            "ai_control": "never",
            "max_runtime_seconds": None,
            "requires_human_ack": False,
        },
    ],
    "scenes": [
        {
            "id": "at_anchor",
            "name": "At Anchor",
            "description": "At anchor configuration: anchor + cockpit + courtesy lights.",
            "actions": [
                {"device_id": "anchor_light", "state": True},
                {"device_id": "cockpit_lights", "state": True},
                {"device_id": "salon_lights", "state": False},
                {"device_id": "courtesy_lights", "state": True},
                {"device_id": "nav_lights", "state": False},
            ],
        },
        {
            "id": "night_mode",
            "name": "Night Mode",
            "description": "Night mode for cabins and courtesy lights.",
            "actions": [
                {"device_id": "salon_lights", "state": False},
                {"device_id": "cabin_lights", "state": True},
                {"device_id": "cockpit_lights", "state": False},
                {"device_id": "courtesy_lights", "state": True},
            ],
        },
        {
            "id": "underway",
            "name": "Underway",
            "description": "Underway running lights configuration.",
            "actions": [
                {"device_id": "nav_lights", "state": True},
                {"device_id": "anchor_light", "state": False},
                {"device_id": "cockpit_lights", "state": True},
                {"device_id": "salon_lights", "state": False},
            ],
        },
        {
            "id": "harbour_mode",
            "name": "In Harbour",
            "description": "Harbour mode lighting.",
            "actions": [
                {"device_id": "nav_lights", "state": False},
                {"device_id": "anchor_light", "state": False},
                {"device_id": "cockpit_lights", "state": True},
                {"device_id": "salon_lights", "state": True},
                {"device_id": "courtesy_lights", "state": True},
            ],
        },
    ],
}
